<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net6.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <PlatformTarget>AnyCPU</PlatformTarget>
	  <Prefer32Bit>true</Prefer32Bit>
	  <!-- Add this -->
	  <NoWarn>NU1605</NoWarn>
	  <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="11.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="dotenv.net" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.35" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.35" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.35">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.35" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.35" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.18" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.3.0" />
	  <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
	  <PackageReference Include="System.Text.Encoding.Extensions" Version="4.3.0" />
	  <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
	  <PackageReference Include="System.Net.Primitives" Version="4.3.0" />
	  <PackageReference Include="Microsoft.Win32.Primitives" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PointOfSale.Business\PointOfSale.Business.csproj" />
    <ProjectReference Include="..\PointOfSale.Model\PointOfSale.Model.csproj" />
	  <None Update="Utilities\LibraryPDF\64bit\libwkhtmltox.dll">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Utilities\LibraryPDF\32bit\libwkhtmltox.dll">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Utilities\LibraryPDF\32bit\" />
    <Folder Include="wwwroot\Logo\" />
	<Folder Include="logs\" />
	  <!-- Add this -->

  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>

</Project>